version: "3"

services:
  jenkins:
    image: jenkins/jenkins:2.380
    container_name: jenkins
    restart: always
    user: root
    privileged: true
    ports:
      - "18080:8080" # Change the external port to 18080
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  gitlab:
    image: gitlab/gitlab-ce:15.3.3-ce.0
    container_name: gitlab
    restart: always
    hostname: 'dev.nfttown.io'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://dev.nfttown.io:9090'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "9090:80" # Change the external port to 9090
      - "443:443"
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

volumes:
  jenkins_home:
  gitlab_config:
  gitlab_logs:
  gitlab_data: