name: docker-deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  docker-ssh-action:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 30s
          script: |
            cd ~/git/amz-erp
            git pull
            docker compose -p amz-erp down --rmi all
            docker compose -p amz-erp up -d
